In [1182]:
import importlib
import numpy
from scripts import NN
from scripts import io
import math as m
importlib.reload(NN)
importlib.reload(io)
import random as rand

In [1120]:
range(10,1
     )

range(10, 1)

In [1121]:
setup = [8,3,8]
alpha = 0.5
lamba = 0 #0.1 is good
batch_size = 500 
bias  = 1
test_NN = NN.NeuralNetwork(setup,NN.activation,alpha,lamba,batch_size,bias)

In [1115]:
test_NN.get_single_input([0,0,0,0,1,0,0,0])
test_NN.feedforward()
print("beginning output",test_NN.layer_a[1])
print("beginning edge matrices",test_NN.edge_matrices)
print("beginning biases",test_NN.biases)

beginning output [0.50128714 0.49928878 0.49845851 0.49684476 0.50694181 0.50334066
 0.49926478 0.49655854]
beginning edge matrices [array([[ 0.00650296,  0.00551604,  0.0114284 ,  0.01355279, -0.00869043,
        -0.01414708,  0.01031349,  0.01396521],
       [ 0.01126441,  0.00171739,  0.0089979 , -0.01525815, -0.00550799,
         0.00758793,  0.00100932, -0.01210404],
       [ 0.0136908 ,  0.02444211, -0.01609706,  0.00313769,  0.01193234,
        -0.02027193, -0.00280215, -0.00550992]]), array([[-0.00807972,  0.01012265, -0.00371897],
       [ 0.00160664, -0.0037523 , -0.00573967],
       [-0.01149291,  0.00114549, -0.00186755],
       [-0.01002888,  0.0056873 , -0.01378045],
       [ 0.01526199,  0.00891817,  0.01403473],
       [ 0.00415287,  0.00841683,  0.00127555],
       [ 0.00030081, -0.00098116,  0.00336071],
       [-0.00748888,  0.00761323,  0.00279018]])]
beginning biases [array([-0.00649088, -0.01030009,  0.01155076]), array([ 6.01775259e-03,  1.12275335e-03, -8.662188

In [1050]:
test_NN.layer_z

[array([-0.00381447, -0.00307658,  0.02832413]),
 array([-0.01516339, -0.01051464, -0.01488656, -0.01218689, -0.00059767,
        -0.00539187, -0.02374283,  0.00143058])]

In [1051]:
test_NN.layer_a

[array([0.49904638, 0.49923086, 0.50708056]),
 array([0.49620922, 0.49737136, 0.49627843, 0.49695331, 0.49985058,
        0.49865204, 0.49406457, 0.50035765])]

In [1116]:
test_NN.test_backprop()

[array([[-0.        , -0.        , -0.        , -0.        , -0.00143498,
        -0.        , -0.        , -0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.00060795,
         0.        ,  0.        ,  0.        ],
       [-0.        , -0.        , -0.        , -0.        , -0.00098241,
        -0.        , -0.        , -0.        ]]), array([[ 0.06218485,  0.06216522,  0.06339617],
       [ 0.06193724,  0.06191768,  0.06314374],
       [ 0.06183378,  0.06181426,  0.06303827],
       [ 0.06163173,  0.06161227,  0.06283227],
       [-0.06115266, -0.06113335, -0.06234388],
       [ 0.06243722,  0.0624175 ,  0.06365346],
       [ 0.06193425,  0.0619147 ,  0.0631407 ],
       [ 0.06159576,  0.06157631,  0.06279561]])]
[array([-0.00143498,  0.00060795, -0.00098241]), array([ 0.12532095,  0.12482194,  0.12461344,  0.12420624, -0.12324079,
        0.12582955,  0.12481593,  0.12413376])]


In [774]:
training_batch = []
batch_number = 1
input_size   = 8
for i in range(batch_number):
    temp_input = numpy.zeros((input_size))
    rand_index = int(numpy.floor(rand.random()*8)-1)
    #print(rand_index)
    temp_input[rand_index] = 1
    #print(temp_input)
    #temp_input = [0,0,1,0,1,1,1,0]        
    training_batch.append(temp_input)    


In [1117]:
test_NN.get_training_set(training_batch)

TypeError: get_training_set() missing 1 required positional argument: 'answers'

In [1124]:
epoch_number = 100000
cost_list = []
for j in range(epoch_number):
    training_batch = numpy.zeros((input_size))
    rand_index = int(numpy.floor(rand.random()*8)-1)
    training_batch[rand_index] = 1
    training_batch = [training_batch]
    training_answer = training_batch
    #print(training_batch)
    test_NN.get_training_set(training_batch,training_answer)
    cost_list.append(test_NN.batch_descent())
    #print("j is ",j,end='\r')

In [1125]:
test_NN.get_single_input([0,0,0,0,0,0,1,0])
test_NN.feedforward()
print("final output",test_NN.layer_a)
print("final edge matrices",test_NN.edge_matrices)
print("final biases",test_NN.biases)

final output [array([0.00295889, 0.97076234, 0.5204794 ]), array([2.29180528e-02, 2.95550898e-05, 2.34611366e-03, 9.30497717e-07,
       4.42116663e-08, 1.26748286e-02, 9.66668891e-01, 3.05259783e-02])]
final edge matrices [array([[-0.01466662,  6.38421816, -4.99823637,  3.49635405,  1.50016745,
        -2.66692978, -5.28523594,  1.05931228],
       [ 3.07567437,  2.33985147, -3.8349551 , -4.88779491, -4.41840468,
        -1.7570223 ,  3.90764627,  5.21559167],
       [-5.63778222, -0.70385175, -2.57388536,  2.88535918, -4.52840416,
         4.54239708,  0.22475133,  5.61954945]]), array([[ -2.74869068,   8.6556197 , -16.22621774],
       [ 13.37432084,   5.20722909,  -4.07643751],
       [-11.10256792,  -6.60615184,  -7.28951489],
       [  7.72329125,  -7.94410364,   6.17517663],
       [  9.30930168,  -8.64424605, -10.64806599],
       [ -8.96739362,  -4.66771399,   9.55146183],
       [-14.92849002,   9.04620683,   2.28091129],
       [  2.57296612,   7.35921929,  10.29858229]])]
f

In [1023]:
test_NN.feedforward()
test_NN.layer_a[2]

IndexError: list index out of range

In [501]:
test_NN.biases

[array([1., 1., 1.]),
 array([1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1.])]

In [676]:
test_NN.test_backprop()

errors are  [array([-0.00060107, -0.00036175, -0.00107644]), array([ 0.14460224,  0.14386716, -0.05266448,  0.14382756, -0.05353651,
       -0.0523875 , -0.05208211,  0.14391227])]
[array([[-0.00043551, -0.00043885, -0.00043982, -0.00043902, -0.00043819,
        -0.00044034, -0.00044091, -0.00043866],
       [-0.00026211, -0.00026412, -0.0002647 , -0.00026422, -0.00026372,
        -0.00026501, -0.00026536, -0.000264  ],
       [-0.00077995, -0.00078592, -0.00078766, -0.00078623, -0.00078473,
        -0.00078859, -0.00078961, -0.00078557]]), array([[ 0.10563829,  0.10521293,  0.10541185],
       [ 0.10510127,  0.10467808,  0.10487599],
       [-0.03847372, -0.0383188 , -0.03839125],
       [ 0.10507235,  0.10464927,  0.10484712],
       [-0.03911077, -0.03895329, -0.03902694],
       [-0.03827137, -0.03811727, -0.03818933],
       [-0.03804827, -0.03789506, -0.03796671],
       [ 0.10513423,  0.1047109 ,  0.10490887]])]
[array([-0.00060107, -0.00036175, -0.00107644]), array([ 0.14460224

In [309]:
test_NN.

In [310]:
for layer in setup:
    input_layers.append(numpy.zeros((layer[0],1)))

In [311]:
input_layers[0][0][0]

0.0

In [312]:
x = [0,10,20]
y = [2,5,20]
x=numpy.array(x)
print(numpy.transpose(x))
print(x)
x*y

[ 0 10 20]
[ 0 10 20]


array([  0,  50, 400])

In [751]:
range[10,1,-1]

TypeError: 'type' object is not subscriptable

In [1133]:
with open('data/yeast-upstream-1k-negative.fa') as f:
    lines = f.readlines()

In [1189]:
lines[0][0] == '>'

True

In [1186]:
len(test_1)

3161

In [1154]:
test_encode = ['AAA','CCC','GGG','TTT']
io.one_hot_encode(test_encode)

[array([1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.]),
 array([0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1.]),
 array([0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0.]),
 array([0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.])]

In [1167]:
test = io.import_positives('data/rap1-lieb-positives.txt')

In [1183]:
test_1 = io.import_negatives('data/yeast-upstream-1k-negative.fa',17)

In [1161]:
io.one_hot_encode(test[0:3])

[array([0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0.,
        0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0.]),
 array([0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0.,
        0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
        0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1.,
        0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0.]),
 array([0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0.,
        0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1.])]

In [1170]:
56908/18

3161.5555555555557

In [1192]:
test = [1,3]
test1 = [4,5]
final = test + test1


In [1193]:
final

[1, 3, 4, 5]