In [1107]:
import importlib
import numpy
from scripts import NN
import math as m
importlib.reload(NN)
import random as rand

In [1108]:
range(10,1
     )

range(10, 1)

In [1109]:
setup = [8,3,10,3,8]
alpha = 0.5
lamba = 0 #0.1 is good
batch_size = 500 
bias  = 1
test_NN = NN.NeuralNetwork(setup,NN.activation,alpha,lamba,batch_size,bias)

In [1094]:
test_NN.get_single_input([0,0,0,0,1,0,0,0])
test_NN.feedforward()
print("beginning output",test_NN.layer_a[1])
print("beginning edge matrices",test_NN.edge_matrices)
print("beginning biases",test_NN.biases)

beginning output [0.49523957 0.49337131 0.49782788 0.49896325 0.50357438]
beginning edge matrices [array([[-0.00908005, -0.00020787, -0.00107989, -0.01129931, -0.00942343,
         0.01318538, -0.00711743,  0.00192067],
       [-0.00364329,  0.00144562, -0.01963996,  0.00035602,  0.00288464,
         0.01095352, -0.01166862,  0.00980897],
       [ 0.00427729,  0.01657441, -0.0016008 , -0.00963579, -0.0070701 ,
        -0.00096107, -0.00894151, -0.01276436]]), array([[-0.01160009,  0.00151589, -0.00614014],
       [-0.01732009, -0.00045895, -0.00880474],
       [-0.00412979,  0.00868638,  0.0123321 ],
       [-0.00647431, -0.00701849,  0.0084651 ],
       [-0.01106188,  0.00913184, -0.01190116]]), array([[-0.00044579, -0.00143212, -0.00184701,  0.00588286, -0.00797559],
       [ 0.00983017, -0.0022643 , -0.00053632,  0.01212461,  0.00137493],
       [ 0.00213601, -0.00164485, -0.00446453,  0.01067999, -0.00320248],
       [ 0.00351324,  0.00933518,  0.01057976, -0.00541531,  0.00332442]

In [1050]:
test_NN.layer_z

[array([-0.00381447, -0.00307658,  0.02832413]),
 array([-0.01516339, -0.01051464, -0.01488656, -0.01218689, -0.00059767,
        -0.00539187, -0.02374283,  0.00143058])]

In [1051]:
test_NN.layer_a

[array([0.49904638, 0.49923086, 0.50708056]),
 array([0.49620922, 0.49737136, 0.49627843, 0.49695331, 0.49985058,
        0.49865204, 0.49406457, 0.50035765])]

In [1095]:
test_NN.test_backprop()

[array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  7.78029213e-14,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  2.39000817e-12,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [-0.00000000e+00, -0.00000000e+00, -0.00000000e+00,
        -0.00000000e+00, -6.13657173e-13, -0.00000000e+00,
        -0.00000000e+00, -0.00000000e+00]]), array([[-2.28772669e-11, -2.24528899e-11, -2.25922482e-11],
       [-1.76915101e-11, -1.73633297e-11, -1.74710987e-11],
       [ 1.94887127e-10,  1.91271939e-10,  1.92459106e-10],
       [-2.82698024e-10, -2.77453930e-10, -2.79176003e-10],
       [ 1.30148783e-10,  1.27734502e-10,  1.28527312e-10]]), array([[-1.10802991e-08, -1.10384995e-08, -1.11382091e-08,
        -1.11636114e-08, -1.12667791e-08],
       [-2.01468798e-08, -2.00708770e-08, -2.02521753e-08,
        -2.02983633e-08, -2.04859490e-08],
       [

In [774]:
training_batch = []
batch_number = 1
input_size   = 8
for i in range(batch_number):
    temp_input = numpy.zeros((input_size))
    rand_index = int(numpy.floor(rand.random()*8)-1)
    #print(rand_index)
    temp_input[rand_index] = 1
    #print(temp_input)
    #temp_input = [0,0,1,0,1,1,1,0]        
    training_batch.append(temp_input)    


In [771]:
test_NN.get_training_set(training_batch)

In [1110]:
epoch_number = 900000
cost_list = []
for j in range(epoch_number):
    training_batch = numpy.zeros((input_size))
    rand_index = int(numpy.floor(rand.random()*8)-1)
    training_batch[rand_index] = 1
    training_batch = [training_batch]
    #print(training_batch)
    test_NN.get_training_set(training_batch)
    cost_list.append(test_NN.batch_descent())
    #print("j is ",j,end='\r')

In [1112]:
test_NN.get_single_input([0,0,0,0,0,0,1,0])
test_NN.feedforward()
print("final output",test_NN.layer_a)
print("final edge matrices",test_NN.edge_matrices)
print("final biases",test_NN.biases)

final output [array([0.99186843, 0.99087831, 0.99236114]), array([0.87413878, 0.97757795, 0.99999995, 0.58535146, 0.85535832,
       0.78590097, 0.93899046, 0.58603218, 0.96351527, 0.58675349]), array([7.76358905e-10, 1.87263118e-08, 4.48950958e-04]), array([9.23476065e-07, 1.05580898e-07, 7.97210578e-04, 3.00994164e-14,
       4.65179123e-01, 1.06390232e-02, 9.16296541e-01, 1.38557102e-10])]
final edge matrices [array([[-4.57276976, -6.70582118,  3.17902506,  4.22608931,  2.97748441,
         2.11003294,  4.02529434, -4.45953417],
       [ 4.15283592, -5.75782155, -5.26242648, -4.07318506,  4.17177608,
         3.40046701,  4.73474322, -1.43206466],
       [-1.99041411, -4.53535999, -3.04719472,  2.8859978 ,  0.79813329,
        -2.42194346,  5.88125858,  1.38589795]]), array([[ 2.66783674,  4.37075772,  1.70700245],
       [ 0.9880667 ,  8.89295738, -0.30906427],
       [ 4.6382058 ,  7.98809111,  6.20768156],
       [ 1.20246284,  2.39036672,  2.81226675],
       [ 2.51497375,  4.21

In [1023]:
test_NN.feedforward()
test_NN.layer_a[2]

IndexError: list index out of range

In [501]:
test_NN.biases

[array([1., 1., 1.]),
 array([1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1.])]

In [676]:
test_NN.test_backprop()

errors are  [array([-0.00060107, -0.00036175, -0.00107644]), array([ 0.14460224,  0.14386716, -0.05266448,  0.14382756, -0.05353651,
       -0.0523875 , -0.05208211,  0.14391227])]
[array([[-0.00043551, -0.00043885, -0.00043982, -0.00043902, -0.00043819,
        -0.00044034, -0.00044091, -0.00043866],
       [-0.00026211, -0.00026412, -0.0002647 , -0.00026422, -0.00026372,
        -0.00026501, -0.00026536, -0.000264  ],
       [-0.00077995, -0.00078592, -0.00078766, -0.00078623, -0.00078473,
        -0.00078859, -0.00078961, -0.00078557]]), array([[ 0.10563829,  0.10521293,  0.10541185],
       [ 0.10510127,  0.10467808,  0.10487599],
       [-0.03847372, -0.0383188 , -0.03839125],
       [ 0.10507235,  0.10464927,  0.10484712],
       [-0.03911077, -0.03895329, -0.03902694],
       [-0.03827137, -0.03811727, -0.03818933],
       [-0.03804827, -0.03789506, -0.03796671],
       [ 0.10513423,  0.1047109 ,  0.10490887]])]
[array([-0.00060107, -0.00036175, -0.00107644]), array([ 0.14460224

In [309]:
test_NN.

In [310]:
for layer in setup:
    input_layers.append(numpy.zeros((layer[0],1)))

In [311]:
input_layers[0][0][0]

0.0

In [312]:
x = [0,10,20]
y = [2,5,20]
x=numpy.array(x)
print(numpy.transpose(x))
print(x)
x*y

[ 0 10 20]
[ 0 10 20]


array([  0,  50, 400])

In [751]:
range[10,1,-1]

TypeError: 'type' object is not subscriptable